import json


class AssessmentPromptBuilder:

    @staticmethod
    def build(security_report: dict) -> str:
        report_json = json.dumps(security_report, indent=2)

        prompt = f"""
You are a Principal Application Security Engineer reviewing an automated security scan report.

This report was generated by a multi-engine security system that performs:
- Static Application Security Testing (SAST)
- Dependency and supply-chain vulnerability scanning
- Secret detection
- Risk scoring and release gating

You must analyze the report as if it were produced by a professional AppSec platform.

Rules:
- Use ONLY the information provided in the report.
- Do NOT invent vulnerabilities.
- Do NOT assume context that is not present.
- Treat the findings as factual.
- Explain risk in business and security terms.

Your response must be structured exactly as follows:

---

## 1. Overall Security Posture
Classify risk as one of:
Low / Medium / High / Critical  
Explain in 2–3 sentences.

## 2. Release Readiness
Is this repository safe for production deployment?  
Answer: YES or NO  
Explain clearly.

## 3. Top Security Risks
List the top 3 risks in descending severity.  
For each:
- What the issue is
- Why it is dangerous
- Potential impact if exploited

## 4. Weakest Security Area
Which category is weakest?
- Code (SAST)
- Dependencies (Supply chain)
- Secrets (Credential exposure)

Explain why.

## 5. Immediate Remediation Actions
Provide a prioritized action plan:
1. First thing to fix
2. Second thing to fix
3. Third thing to fix

Each action should be short and actionable.

## 6. Executive Summary
Write a 3–4 sentence executive summary suitable for engineering leadership.

---

Here is the security report to analyze:

{report_json}
"""
        return prompt